["PARAMETER"]
additionalModels="SO_Nutzungsplanung_20171118_Validierung_20211006;SO_FunctionsExt"

["SO_Nutzungsplanung_20171118.Rechtsvorschriften.Dokument.TextImWeb"]
type="warning"

["SO_Nutzungsplanung_20171118_Validierung_20211006.Nutzungsplanung_Validierung.v_Grundnutzung.checkMinimumFlaeche"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20211006.Nutzungsplanung_Validierung.v_Ueberlagernd_Flaeche.checkMinimumFlaeche"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20211006.Nutzungsplanung_Validierung.v_Ueberlagernd_Linie.checkMinimumLaenge"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20211006.Erschliessungsplanung_Validierung.v_Erschliessung_Flaechenobjekt.checkMinimumFlaeche"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20211006.Erschliessungsplanung_Validierung.v_Erschliessung_Linienobjekt.checkMinimumLaenge"]
check="warning"